blog/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^blog/$', views.post_list, name='blog'),
    url(r'^blog/(?P<id>\d+)/$', views.post_detail),
    url(r'^post/new/$', views.new_post, name='new_blog_post'),
    url(r'^blog/(?P<id>\d+)/edit$', views.edit_post, name='editblog'),
]

threads/urls.py
from django.conf.urls import url, include
from threads import views as threads_views

urlpatterns = [
    url(r'^forum/$', threads_views.forum, name='forum'),
    url(r'^threads/(?P<subject_id>\d+)/$', threads_views.threads, name='threads'),
    url(r'^new_thread/(?P<subject_id>\d+)/$', threads_views.new_thread, name='new_thread'),
    url(r'thread/(?P<thread_id>\d+)/$', threads_views.thread, name='thread'),
    url(r'^post/new/(?P<thread_id>\d+)/$', threads_views.new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$', threads_views.edit_post, name='edit_post'),
    url(r'^post/delete/(?P<post_id>\d+)/$', threads_views.delete_post, name='delete_post'),
    url(r'^thread/vote/(?P<thread_id>\d+)/(?P<subject_id>\d+)/$', threads_views.thread_vote, name='cast_vote'),
]

we_are_social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
#from settings import MEDIA_ROOT
from settings.staging import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('home.urls')),
    url(r'', include('accounts.urls')),
    url(r'', include('threads.urls')),
    url(r'', include('polls.urls')),
    url(r'', include('locations.urls')),
    url(r'', include('contactform.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^captcha/', include('captcha.urls')),
]

threads/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings

class Subject(models.Model):
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name

class Thread(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads')
    subject = models.ForeignKey(Subject, related_name='threads')
    created_at = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.name

class Post(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    created_at = models.DateTimeField(default=timezone.now)
    def __unicode__(self):
        return str(self.created_at)

polls/forms.py
from django import forms
from .models import Poll, PollSubject

class PollForm(forms.ModelForm):
    question = forms.CharField(label="What is your poll about?", required=False)
    class Meta:
        model = Poll
        fields=['question']

class PollSubjectForm(forms.ModelForm):
    name = forms.CharField(label="Poll Subject Name", required=False)

    def __init__(self, *args, **kwargs):
        super(PollSubjectForm, self).__init__(*args, **kwargs)

        self.empty_permitted = False

    class Meta:
        model = PollSubject
        fields = ['name']

threads/forms.py
from django import forms
from .models import Subject, Thread, Post

class ThreadForm(forms.ModelForm):
    name =forms.CharField(label='Thread Name', widget=forms.TextInput(attrs={'placeholder': 'What is your discussion about?'}))
    is_a_poll = forms.BooleanField(label="Include a Poll?", required=False)
    class Meta:
        model = Thread
        fields = ['name']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['comment']

threads/views.py
from django.shortcuts import render, get_object_or_404
from .models import Subject, Post, Thread
from django.shortcuts import redirect
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from .forms import ThreadForm, PostForm
from django.forms import formset_factory
from polls.forms import PollForm, PollSubjectForm
from polls.models import PollSubject, Poll

def forum(request):
    subjects = Subject.objects.all()
    args = {'subjects': subjects}
    return render(request, 'forum/forum.html', args)

def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    args = {'subject': subject}
    return render(request, 'forum/threads.html', args)

@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    poll_subject_formset = formset_factory(PollSubjectForm, extra=3)
    if request.method == 'POST':
        ispoll = request.POST.get('is_a_poll')
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        if request.POST.get('is_a_poll', None):
            poll_form = PollForm(request.POST)
            poll_subject_formset = poll_subject_formset(request.POST)
            if thread_form.is_valid() and post_form.is_valid() and poll_form.is_valid() and poll_subject_formset.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()
                if request.POST.get('comment', None):
                    post = post_form.save(False)
                    post.user = request.user
                    post.thread = thread
                    post.save()
                poll = poll_form.save(False)
                poll.thread = thread
                poll.save()
                for subject_form in poll_subject_formset:
                    subject = subject_form.save(False)
                    subject.poll = poll
                    subject.save()
                messages.success(request, "Your new thread has been created")
                return redirect(reverse('thread', args={thread.pk}))
        else:
            if thread_form.is_valid() and post_form.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()
                if request.POST.get('comment', None):
                    post = post_form.save(False)
                    post.user = request.user
                    post.thread = thread
                    post.save()
                messages.success(request, "Your new thread has been created")
                return redirect(reverse('thread', args={thread.pk}))
    else:
        thread_form = ThreadForm()
        post_form = PostForm(request.POST)
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset()
    args = {'thread_form': thread_form, 'post_form': post_form, 'subject': subject, 'poll_form': poll_form, 'poll_subject_formset': poll_subject_formset,}
    args.update(csrf(request))
    return render(request,'forum/thread_form.html', args)

def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)

    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'forum/thread.html', args)

@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    if request.method=='POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()
            messages.success(request, "Your post has been added to the thread")
            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()
    args = {'form': form, 'form_action': reverse('new_post', args={thread.id}), 'button_text': 'Update Post', 'thread': thread}
    args.update(csrf(request))
    return render(request,'forum/post_form.html', args)

@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Post, pk=post_id)
    if request.method=='POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "You have updated the thread")
            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)
    args = {'form': form, 'form_action': reverse('edit_post', kwargs={'thread_id': thread.id, 'post_id': post.id}), 'button_text': 'Update Post'}
    args.update(csrf(request))
    return render(request,'forum/post_form.html', args)

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()
    messages.success(request, 'Your Post Has Been deleted')
    return redirect(reverse('thread', args={thread_id}))

@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)
    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You have already votes on this!")
        return redirect(reverse('thread', args={thread_id}))
    subject = PollSubject.objects.get(id=subject_id)
    subject.votes.create(poll=subject.poll, user=request.user)
    messages.success(request, "We have registered your vote!")
    return redirect(reverse('thread', args={thread_id}))

threads/templates/forum/comment_details.html
{% load thread_extras %}
<div class="details">
    <div class="col-md-6">
        <div class="pull-left">
            <time datetime="{{ post.created_at }}">
                Posted: {{ post.created_at|started_time }}
            </time>
        </div>
    </div>
    <div class="col-md-6">
        <div class="pull-right">
            {% if post.user == user or user.is_staff %}
            <a href="{% url 'edit_post' thread.id post.id %}"><i class="fa fa-pencil-square-o fa-2x"></i> </a>
            <a href="{% url 'delete_post' post.id%}"><i class="fa fa-trash-o fa-2x"></i> </a>
            {% endif %}
        </div>
    </div>
    <div class="clearfix"></div>
</div>

threads/templates/forum/forum.html
{% extends 'base.html' %}
{% load thread_extras %}
{% load bootstrap_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block content_header %}
<h1 class="homeHeading">We Are Social - Forum</h1>
<h2 class="homeHeading">This is where YOU get to talk about your ideas</h2>
{% endblock %}
    {% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Forum' '/' %}
    {% endblock %}

{% block content %}

    <div class="container">
    {% render_breadcrumbs %}
    {% for subject in subjects %}
        <article>
            <div class="col-md-12">
                <section class="subject">
                <h2><a href="{% url 'threads' subject.id %}">{{ subject.name }}</a></h2>
                {% autoescape off %}{{ subject.description }}{% endautoescape %}
            </section>
            </div>
            <div class="col-md-4">
                <section><h3>Number of Live Debates in this Forum: <strong>{{ subject|get_total_subject_threads }}</strong></h3></section>
            </div>
            <div class="col-md-4">
                <section><h3>Number of Posts: <strong>{{ subject|get_total_subject_posts }}</strong></h3></section>
            </div>
            <div class="col-md-4">
                <a class="btn btn-info" href="{% url 'threads' subject.id%}">Enter Forum</a>
            </div>
        </article>
{% endfor %}
    </div>
{% endblock %}

threads/templates/forum/post.html
{% load staticfiles %}
{% load emoticons_tags %}
<div class="container">
    <section class="row comment col-md-9">
        <div class="col-md-3 comment-profile">
            <p><img src="{% static 'img/user.png' %}" /></p>
            <p>{{ post.user.username }}</p>
            <p>{{ post.user.posts.count }}</p>
        </div>
        <div class="col-md-9">
            <div class="comment-content">
                {% autoescape off %}
                {{ post.comment|emoticons }}
                {% endautoescape %}
            </div>
            {% include 'forum/comment_details.html' %}
        </div>
    </section>
</div>

threads/templates/forum/post_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block head_js %}
<script src="{% static 'js/tinymce/tinymce.min.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({mode: "textareas", theme: 'modern', plugins: "paste",});
</script>
{% endblock %}
{% block content_header %}
<h1 class="homeHeading">We Are Social - Forum</h1>
<h2 class="homeHeading">{{ thread }}</h2>

{% endblock %}
{% block content %}
<div class="container">
    <section>
        <div class="col-md-9">
            <h2>{{ thread }} - Add your comments below:</h2>
            <form method="post" action="{{ form_action }}">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="{{ button_text }}">
                </div>
            </form>
        </div>
    </section>
</div>
{% endblock %}

threads/templates/forum/thread.html
{% extends 'base.html' %}
{% load thread_extras %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block content_header %}
<h1 class="homeHeading">We Are Social - Forum</h1>
<h2 class="homeHeading">{{ thread.name }}</h2>
    {% if user.is_authenticated %}
    <p><a href="{% url 'new_post' thread.id %}" class="btn btn-primary">Add a Comment</a></p>
    {% endif %}
{% endblock %}
{% autoescape on %}
{% block breadcrumbs %}
{% clear_breadcrumbs %}
{{ block.super }}
{% breadcrumb 'Forum' '/forum/' %}
{% breadcrumb thread.name '/' thread.id '/'%}
{% endblock %}
{% endautoescape %}
{%  block content %}
    <div class="row header">
        <div class="container">
        {% render_breadcrumbs %}
            <h2>{{ thread.name }}</h2>
            <div class="col-md-12">
                <table class="table">
                    <tbody>
                        <tr>
                             <th>CREATED</th>
                             <th>OWNER</th>
                             <th>LAST POST</th>
                        </tr>
                        <tr>
                             <td><time datetime="{{ thread.created_at }}">{{ thread.created_at|started_time }}</time></td>
                             <td>{{ thread.user.username }}</td>
                             <td>{% last_posted_user_name thread %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% if thread.poll %}
            <div class="container">
                <div class="col-md-6">
                    <h2>Poll</h2>
                    <p><strong>{{ thread.poll.question }}</strong></p>
                    <p>The votes so far...</p>
                    {% for subject in thread.poll.subjects.all %}
                        <div class="col-md-10">
                            <strong>{{ subject.name }}</strong>
                            <span class="pull-right">{{ subject|vote_percentage }}</span>
                        </div>
                        {% autoescape off %}
                        {% user_vote_button thread subject user %}
                        {% endautoescape %}
                        <div class="col-md-10">
                            <div class="progress">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-value="{{ subject|vote_percentage }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ subject|vote_percentage }}%;"></div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
     {% if user.is_authenticated %}
            <p><a href="{% url 'new_post' thread.id %}" class="btn btn-primary">Add A Comment</a></p>
     {% endif %}
        </div>
    </div>
    <div class="container">
       {% for post in thread.posts.all %}
         {% include "forum/post.html" %}
       {% endfor %}
    </div>
{% endblock %}

threads/templates/forum/thread_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block head_js %}
<script src="{% static 'js/tinymce/tinymce.min.js' %}" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
    tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})
</script>
<script type="text/javascript">
    $(function(){
        if(!$('#id_is_a_poll').is('checked')) {
            $('#poll_form').hide()

        }
        $('#id_question').removeAttr('required');
        $('#id_is_a_poll').click(function(el) {
            var poll_form = $('#poll_form')
            if(!$('#id_is_a_poll').prop('checked')) {
                console.log("checked")
                poll_form.hide()
                $('#id_question').removeAttr('required');
            } else {
                console.log("unchecked")
                poll_form.show()
                $('#id_question').attr('required', 'required');
            }
        })
    })
</script>
{% endblock %}
{% block content_header %}
<h1 class="homeHeading">We Are Social - Forum</h1>
<h2 class="homeHeading">Create a Discussion</h2>
{% endblock %}
{% block content %}
<div class="container">
    <section>
        <div class="col-md-9">
            <h3>Create a discussion within this forum, if you like you can add a poll to the discussion to get your fellow members to vote on a subject.</h3>
            <form method="POST" action="{% url 'new_thread' subject.id %}">
                {% csrf_token %}
                <div class="form-group">
                    {{ thread_form|as_bootstrap }}
                    <hr>
                    <p>If you want to you can add a comment to your discussion to get the ball rolling</p>
                    {{ post_form|as_bootstrap }}
                </div>
                <div id="poll_form" class="form-group">
                    {{ poll_form|as_bootstrap }}
                    {{ poll_subject_formset.management_form }}
                    {% for poll_subject_form in poll_subject_formset %}
                        {{ poll_subject_form|as_bootstrap }}
                    {% endfor %}
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Post New Discussion / Idea">
                </div>
            </form>
        </div>
    </section>
</div>
{% endblock %}

threads/templates/forum/threads.html
{% extends 'base.html' %}
{% load thread_extras %}
{% load bootstrap_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block content_header %}
<h1 class="homeHeading">{{ subject.name }}</h1>
<h2 class="homeHeading">{{ subject.name }}</h2>
{% endblock %}
{% block breadcrumbs %}
{% clear_breadcrumbs %}
{{ block.super }}
{% breadcrumb 'Forum' '/forum/' %}
{% breadcrumb subject.name '/' subject.id '/'%}
{% endblock %}
{% block content %}
<div class="container">
    {% render_breadcrumbs %}
    <div class="col-md-12">
    {% if user.is_authenticated %}
        <p><a href="{% url 'new_thread' subject.id %}" class="btn btn-primary">Create A New Discussion / Share An Idea</a> </p>
    {% endif %}
    {% for thread in subject.threads.all %}
        {% include "forum/threads_items.html" %}
    {% endfor %}
    </div>
</div>
{% endblock %}

threads/templates/forum/threads_items.html
<section class="thread">
    <header>
        <table class="table">
            <tr>
                <td><a href="{% url 'thread' thread.id %}"><h4>{{ thread.name }}</h4></a></td>
            </tr>
        </table>
    </header>
</section>